CREATE TABLE public.car (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"mark" varchar(255) NOT NULL,
	"model" varchar(255) NULL,
	cost int8 null,
	CONSTRAINT car_pkey PRIMARY KEY (id)
);

create table public.human(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	age int8 not null,
	rules BOOLEAN not null,
	car_id int8 NULL,
	CONSTRAINT human_pkey PRIMARY KEY (id)
)

ALTER TABLE public.human ADD CONSTRAINT human_car_id_to_car FOREIGN KEY (car_id) REFERENCES public.car(id);
